[project]
name = "sqlanalytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ranyast", email = "ranyast@yahoo.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.5.6",
]

[project.scripts]
dataset-users = "sqlanalytics.dataset_users:main"
dataset-orders = "sqlanalytics.dataset_orders:main"
orders-report = "sqlanalytics.orders_report:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
